services:
  ssh:
    container_name: ssh-user-space
    build: ./ssh/
    ports:
      - 22:22
    volumes:
      - /var/run/docker.sock:/tmp/mimimi/docker.sock

  flask_app:
    build: ./web-server/
    ports:
      - "5000:5000" 

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx
    depends_on:
      - flask_app # Ensure that Flask app starts before Nginx
